apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kavachid.fullname" . }}
  labels:
    {{- include "kavachid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kavachid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kavachid.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "kavachid.fullname" . }}-secret
                  key: database-url
            - name: KAVACHID_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "kavachid.fullname" . }}-secret
                  key: master-key
            - name: WEBHOOK_URL
              value: {{ .Values.config.webhookUrl | quote }}
            - name: JWT_ACCESS_EXPIRES_IN
              value: {{ .Values.config.jwtAccessExpiresIn | quote }}
            - name: JWT_REFRESH_EXPIRES_IN
              value: {{ .Values.config.jwtRefreshExpiresIn | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
