apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kavachid.fullname" . }}-secret
  labels:
    {{- include "kavachid.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.database.url | b64enc | quote }}
  master-key: {{ .Values.config.masterKey | b64enc | quote }}
