name: kavach_flutter
description: The official Kavach Flutter SDK. Provides cross-platform biometric authentication by securely bridging to native iOS FaceID and Android Biometrics.
version: 1.0.4
homepage: https://github.com/Rajeev02/kavachid
repository: https://github.com/Rajeev02/kavachid/tree/main/sdks/kavach-flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0