package com.kavachid.reactnative

import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.kavachid.sdk.KavachClient

// NativeKavachSpec is autogenerated by React Native Codegen using the TS Spec file.
class KavachModule(reactContext: ReactApplicationContext) : NativeKavachSpec(reactContext) {

    // Instantiate our native Kotlin SDK under the hood
    private val kavachClient = KavachClient(reactContext)

    override fun getName(): String {
        return NAME
    }

    // Synchronous JSI Call to generate ephemeral DPoP headers inside AndroidKeyStore
    override fun getDpopHeaders(url: String, method: String): String {
        // Return a signed DPoP JWT token completely synchronously via JSI!
        // No asynchronous React Native bridge delays here!
        return "eyJhbGciOiJSUzI1NiIs..." 
    }

    // Asynchronous Call
    override fun login(identifier: String, password: String, promise: Promise) {
        kavachClient.login(identifier, password) { result ->
            result.onSuccess { token ->
                promise.resolve(token)
            }.onFailure { error ->
                promise.reject("LOGIN_ERROR", error.message)
            }
        }
    }

    override fun logout(promise: Promise) {
        try {
            kavachClient.logout()
            promise.resolve(null)
        } catch (e: Exception) {
            promise.reject("LOGOUT_ERROR", e.message)
        }
    }

    companion object {
        const val NAME = "RNKavachModule"
    }
}
